import {
  faBagShopping,
  faBottleDroplet,
  faBowlFood,
  faClock,
  faGears,
  faGem,
  faGlasses,
  faHandDots,
  faHouse,
  faKey,
  faLaptop,
  faLightbulb,
  faMobileScreenButton,
  faMotorcycle,
  faPersonDress,
  faShirt,
  faShoePrints,
} from "@fortawesome/free-solid-svg-icons"

export const BASE_URL = "https://dummyjson.com/"
export const iconsForNavbar = [
  faMobileScreenButton,
  faLaptop,
  faBottleDroplet,
  faHandDots,
  faBowlFood,
  faHouse,
  faKey,
  faShirt,
  faPersonDress,
  faShoePrints,
  faShirt,
  faShoePrints,
  faClock,
  faClock,
  faBagShopping,
  faGem,
  faGlasses,
  faGears,
  faMotorcycle,
  faLightbulb,
]
